config/routes.rb
Launchbox::Application.routes.draw do
  root :to => "apps#index"
  resources :apps do
    resources :comments
    resources :props
  end

end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :codebase_url, :email, :name, :props, :url, :description
  has_many :comments
  has_many :props

  validates_presence_of :name, :email, :url, :codebase_url, :description
  validates_format_of :email, :with => /@/
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :text, :app_id
  belongs_to :app

  validates_presence_of :email, :first_name, :last_name, :text
end

app/models/prop.rb
class Prop < ActiveRecord::Base
  attr_accessible :app_id
  belongs_to :app

  validates_presence_of :app_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])
    @comment = Comment.new
    @prop = Prop.new

    respond_to do |format|
      # format.html # show.html.erb
      format.html
      format.json { render json: @app }
    end
   rescue ActiveRecord::RecordNotFound
      redirect_to apps_path, notice: "App Not Found"
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render json: @app, status: :created, location: @app }
      else
        format.html { render action: "new" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_app

  # GET /comments
  # GET /comments.json

  def index
    @comments = @app.comments.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = @app.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = @app.comments.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = @app.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @app.comments.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @app, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = @app.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to [@app, @comment], notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = @app.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to app_comments_url(@app) }
      format.json { head :no_content }
    end
  end

  private

    def load_app
      @app = App.find(params[:app_id])
    end
end

app/controllers/props_controller.rb
class PropsController < ApplicationController
  # GET /props
  # GET /props.json
  def index
    @props = Prop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @props }
    end
  end

  # GET /props/1
  # GET /props/1.json
  def show
    @prop = Prop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prop }
    end
  end

  # GET /props/new
  # GET /props/new.json
  def new
    @app = App.find(params[:app_id])
    @prop = @app.props.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prop }
    end
  end

  # GET /props/1/edit
  def edit
    @prop = Prop.find(params[:id])
  end

  # POST /props
  # POST /props.json
  def create
    @app = App.find(params[:app_id])
    @prop = @app.props.new(params[:prop])

    respond_to do |format|
      if @prop.save
        format.html { redirect_to app_path(@app), notice: 'Prop was successfully created.' }
        format.json { render json: @prop, status: :created, location: @prop }
      else
        format.html { render action: "new" }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /props/1
  # PUT /props/1.json
  def update
    @prop = @app.props.find(params[:id])

    respond_to do |format|
      if @prop.update_attributes(params[:prop])
        format.html { redirect_to @prop, notice: 'Prop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /props/1
  # DELETE /props/1.json
  def destroy
    @prop = Prop.find(params[:id])
    @prop.destroy

    respond_to do |format|
      format.html { redirect_to props_url }
      format.json { head :no_content }
    end
  end

  private

  def load_app
    @app = App.find(params[:app_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/props_helper.rb
module PropsHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="app-submit-form">
  <div class="field">
    <%= f.label :name, "Name:" %><br />
    <%= f.text_field :name, class: 'input-block-level' %>
  </div>
  <div class="field">
    <%= f.label :url, "URL:" %><br />
    <%= f.text_field :url, class: 'input-block-level' %>
  </div>
  <div class="field">
    <%= f.label :email, "Email:" %><br />
    <%= f.text_field :email, class: 'input-block-level' %>
  </div>
  <div class="field">
    <%= f.label :codebase_url, "Codebase URL:" %><br />
    <%= f.text_field :codebase_url, class: 'input-block-level' %>
  </div>
  <div class="field">
    <%= f.label :description, "Description:" %><br />
    <%= f.text_area :description, class: 'input-block-level' %>
  </div>
  <div class="actions">
    <%= f.submit "Submit App", class: "btn btn-large" %>
  </div>
</div>
<% end %>

app/views/apps/edit.html.erb
<div class= "container">
  <div class= "row">
     <div class="offset3 span6">
        <h1>Editing app</h1>
      </div>
  </div>

  <div class= "row">
      <div class="offset3 span6">
        <%= render 'form' %>

        <%= link_to 'Show', @app %> |
        <%= link_to 'Back', apps_path %>

      </div>
  </div>
  
</div>      

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>
<div class= "container">
    <div class= "row">
        <div class="span8">
            <h1>LaunchBox</h1>
        </div>
        <div class="span4">
            <%= button_to 'Submit your app', new_app_path, class: "btn btn-info btn-large", method: :get %>
        </div>
    </div>

    <div class="row">
        <div class="span12">
            <img src="/assets/launchbox.jpg">
        </div>
    </div>
</div>
 <div class="container2">
        <div class="row">
            <div class="span12">
                <table class= "table">
                  <tr>
                    <th>Name</th>
                    <th>Url</th>
                    <th>Email</th>
                    <th>Codebase url</th>
                    <th>Props</th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                <% @apps.each do |app| %>
                  <tr>
                    <td><%= app.name %></td>
                    <td><%= app.url %></td>
                    <td><%= app.email %></td>
                    <td><%= app.codebase_url %></td>
                    <td><%= app.props.count %></td>
                    <td><%= link_to 'Show', app %></td>
                    <td><%= link_to 'Edit', edit_app_path(app) %></td>
                    <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
                </table>
            </div>
        </div>
        <div class="footer"><p>&copy;Launchbox</p></div>
    </div>

app/views/apps/new.html.erb
<div class= "container">
    <div class= "row">
     <div class="offset3 span6">
        <h1>Prepare for Liftoff</h1>
      </div>
    </div>
    <br />

    <div class= "row">
      <div class="offset3 span6">
        <%= render 'form' %>

        <%= link_to 'Back', apps_path %>

      </div>
    </div>
</div>

app/views/apps/show.html.erb
<div class= "container">
  <div class= "row">
     <p id="notice"><%= notice %></p>
      <div class="span8">
          <h1>LaunchBox</h1>
      </div>
      <div class="span4">&nbsp;</div>
  </div>
  <div class="row">
    <div class="span12">
      <img src="/assets/launchbox.jpg">
    </div>
  </div>
  <div class= "row">
    <div class="span12">
      <h3> <%= @app.name %> </h3>
    </div>
  </div>
  <div class="row">
    <div class="span6">
      <p>
        <b>URL: </b><%= @app.url %>
      </p>
      <p>
        <b>Email: </b><%= @app.email %>
      </p>
      <p>
        <b>Codebase URL: </b><%= @app.codebase_url %>
      </p>
      <p>
        <b>Description: </b><%= @app.description %>
      </p>
    </div>
    <div class="span3">
    </div>
    <div class="span2">
      <div class="pull-right"><%= render 'props/form' %></div>
    </div>
    <div class="span1 pad-top">
      <div class="my-label">
        <%= @app.props.count %>
      </div>
    </div>
  </div>
        <br />
        <h4>Comments</h4>
        <hr />
        <% @app.comments.each do |comment| %>
        <div class="row comments-section">
          <div class="offset1 span2">
            <span class="commenter"><%= comment.first_name %> <%= comment.last_name %> said:<span>
          </div>
          <div class="span8">
           <span class="comment-text"><%= comment.text %></span>
         </div>
       </div>
       <div class="row">
        <div class="offset1 span10">
          <hr />
        </div>
       </div>
      <% end %>

  <div class="row">
    <div class="offset2 span6">
      <%= render 'comments/form' %>
    </div>
  </div>

    </div>
  </div>
  <div class="row">
    <div class="offset6 span4">
      <%= link_to 'Edit', edit_app_path(@app) %> |
      <%= link_to 'Back', apps_path %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@app, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h3>Submit a comment</h3>

<div class="comment-submit-form">
    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name, class: 'input-block-level' %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name, class: 'input-block-level'  %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email, class: 'input-block-level'  %>
    </div>
    <div class="field">
      <%= f.label :text, 'Comment' %><br />
      <%= f.text_area :text, class: 'input-block-level'  %>
    </div>

    <div class="actions">
      <%= f.submit 'Submit Comment', class: "btn" %>
    </div>
    <% end %>
</div>

app/views/comments/_load_comments.html.erb
<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.text %></td>
    <td><%= comment.first_name %></td>
    <td><%= comment.last_name %></td>
    <td><%= comment.email %></td>
    <td><%= link_to 'Show', app_comment_path(@app, comment) %></td>
    <td><%= link_to 'Edit', edit_app_comment_path(@app, comment) %></td>
    <td><%= link_to 'Destroy', [@app, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', app_comment_path(@app, @comment) %> |
<%= link_to 'Back', app_comments_path(@app) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Text</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.text %></td>
    <td><%= comment.first_name %></td>
    <td><%= comment.last_name %></td>
    <td><%= comment.email %></td>
    <td><%= link_to 'Show', app_comment_path(@app, comment) %></td>
    <td><%= link_to 'Edit', edit_app_comment_path(@app, comment) %></td>
    <td><%= link_to 'Destroy', [@app, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_app_comment_path(@app) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', app_comments_path(@app) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @comment.text %>
</p>

<p>
  <b>First name:</b>
  <%= @comment.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @comment.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @comment.email %>
</p>


<%= link_to 'Edit', edit_app_comment_path(@app, @comment) %> |
<%= link_to 'Back', app_comments_path(@app) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Launchbox</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/props/_form.html.erb
<%= form_for([@app, @prop]) do |f| %>
  <% if @prop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prop.errors.count, "error") %> prohibited this prop from being saved:</h2>

      <ul>
      <% @prop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :app_id %>
  </div>
  <div class="actions">
    <%= f.submit "Give Props" %>
  </div>
<% end %>

app/views/props/edit.html.erb
<h1>Editing prop</h1>

<%= render 'form' %>

<%= link_to 'Show', @prop %> |
<%= link_to 'Back', props_path %>

app/views/props/index.html.erb
<h1>Listing props</h1>

<table>
  <tr>
    <th>App</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @props.each do |prop| %>
  <tr>
    <td><%= prop.app_id %></td>
    <td><%= link_to 'Show', prop %></td>
    <td><%= link_to 'Edit', edit_prop_path(prop) %></td>
    <td><%= link_to 'Destroy', prop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prop', new_prop_path %>

app/views/props/new.html.erb
<h1>New prop</h1>

<%= render 'form' %>

<%= link_to 'Back', app_props_path(@app) %>

app/views/props/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>App:</b>
  <%= @prop.app_id %>
</p>


<%= link_to 'Edit', edit_prop_path(@prop) %> |
<%= link_to 'Back', props_path %>